language: python
python: 3.6
before_install: sudo pip install -r requirements.txt
script: coverage run --source=asyncDownloader setup.py test
env:
  global:
    secure: B1Gucmd3ApFecdEhqXVRP3XUCiv1RXn7+ok6z57rXsV/uhTcWQwFRbvS28qmcuJRQgHkiL3I/2gFPARg0Y0NhYeA3NH8UYDlEsFMDMDiD2jaiEH3F/eUoSUFENw8dOJ5bpoZ32UXcHzM+58SihhGit3DW186b5XeWGWsPcIDtYSfekmnY4eJwSwUqs7WB5MCltnG5lwVsMQcWb6j6c94y8gGfFqvsW6Pcew4sHik82AUx0354ZYG0cesvYsAaJmbLlOCmHumidA8tOUBdM2PXHUwPPdIQzG+987KesBDJV2ZfZhFwdcGky7C4TM/v9vcNhCR3b4Ojo6SZEKwo0C6UnIGm5WkDQnOoxDKmFyqWCCL2bYcuz7eomRfv8PvlllGCBhwIAcI5QoM119TO5Ck5cQ/UUvI2kRXGgKHrNrYkYpr2TXE4tE47NyDeGRen3tP5JhGjMUwzHso+lD3+NE6gLYThZunqCL5KnpRSNqSHFyAVDZySyp274d/zmt9N5ZHZu92o6CcI6fiB6GReHxeFmy1sSTbnPFE7v3DV2Lwz0fU68e1cjvIrcX/cV96l0m9ej0TnxkrSFoKFkE1r6BENQO1sv1khA2aWz+bVHbVJiByQmFHUpD1zSqqu6anp8t2611xuPxznL2QxdSr43SFOmA60NY/eqz6GI7rSgixMVU=
after_success: coveralls
